# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3778188e23bb87580e1a8e5f76c98bdaeacc67501eecadfba981bfe4e96a06278ba35d4fb3104859f542253f00d2a995142e1014f23c4e5e4c1c9c60f83d8bde

test:
  secret_key_base: a49150ec20710a881209f26b1bbe1787af082bc3e9a2299e278724167ae9d0797bafc72320198b7657de9f05c1e0cd1d31b31727f06f4bf970afb1ba5b437486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
